### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by PoojaG20** [akoscz/YouTubePlaylist#14] opened 2016-07-23 13:19 UTC
Process: com.sensentouch.playyoutube, PID: 13054
                                                   java.lang.NullPointerException
                                                       at com.package.playyoutube.YouTubeRecyclerViewFragment$1.onPostExecute(YouTubeRecyclerViewFragment.java:99)
                                                       at com.package.playyoutube.YouTubeRecyclerViewFragment$1.onPostExecute(YouTubeRecyclerViewFragment.java:94)
                                                       at android.os.AsyncTask.finish(AsyncTask.java:632)
                                                       at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                                                       at android.os.Handler.dispatchMessage(Handler.java:110)
                                                       at android.os.Looper.loop(Looper.java:193)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5299)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
                                                       at dalvik.system.NativeStart.main(Native Method)

I used firstly Android API KEY then i found it works on Browser Key But when i even used Browser key it still gives me same error Please can you help me out

**Comment by akoscz** [comment] 2017-03-05 04:33
duplicate of #12

**Closed by akoscz** 2017-03-05 04:33 UTC
